name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      run: |
          pip install pyinstaller
          pyinstaller src/vltava-scraper.py --onefile

    - uses: actions/upload-artifact@v2
      with:
        name: vltava-scraper
        path: src/dist/